- install.sh
`yum_repo` mistakenly was hardcoded to `centos` now it should be based
off of `$lsb_dist`
> Make yum repo point to correct lsb_dist

- .gitignore
- Makefile
.log files didn't work correctly when evaluating possible docker images
to run so I removed the suffix portion. Also made it easier to run for
specific distros ala:
`make DISTROS="fedora-25 fedora-24 centos-7" CHANNEL_TO_TEST=edge EXPECTED_VERSION="17.06.0-ce" EXPECTED_GITCOMMIT="02c1d87" clean check`
> Make testing working again!

- install.sh
The script doesn't have official versions but I think it would be smart
to add a commit sha to the script so that when issues can be tracked to
a specific sha of the script.
> Adds sha to script

- Jenkinsfile
- Makefile
- verify-docker-install
The install script won't be updated every single time a release is done
so it does not make sense to tie the verification jobs to specific
versions / git commits.
> Removes version and git commit verification

- Jenkinsfile
- Makefile
- install.sh
* Removes old raspbian cruft now that raspbian has a repo on
download.docker.com
* Adds a support matrix so that we can have an easier time updating
what architectures/distros we support
* Added support for s390x and aarch64
* Had to change add-apt-repository to an echo into a file, was not
functioning correctly on raspbian see moby/moby#31405
* Update testing pipeline for multiarch
* Removed deprecation warnings for raspbian
> Updates for 17.07.0-ce-rc1

- Jenkinsfile
- Makefile
Ran into an issue with the jenkins build with archiving artifacts. Chose
to remedy this by naming all of the potential artifacts with the same
pattern
> Update verification targets to include arch

- install.sh
Reverts raspbian changes back to https://apt.dockerproject.org, due to
issues with swarm in the newest release 17.07.0-ce related to issue
docker/swarmkit#2294.
This will stay in place for raspbian until that issue is resolved.
ping @alexellis @StefanScherer
> Revert raspbian changes

- install.sh
In order to install docker engine on Ubuntu from China mirror provided by AzureChinaCloud  if mirror option is present.
usage:
sh install --mirror AzureChinaCloud
Without this change, the docker install will always fail on downloading from global site due to network issue.
> Use mirror provided by AzureChinaCloud

- Jenkinsfile
- Makefile
- install.sh
Basically uses the jessie repo for raspbian stretch due to raspbian
jessie download links being taken off the official raspbian site.
This is only a temporary fix and should not be considered permanent
ping @StefanScherer @alexellis
> Adds support for raspbian stretch

- Jenkinsfile
- Makefile
- install.sh
Fedora 24 has reached EOL on August 8, 2017 https://fedoramagazine.org/fedora-24-eol/
> Fedora 24 deprecation notice, reached EOL, adds Fedora 26

- install.sh
Background:
On Centos 7, when command lsb_release available, the dist_version evaluated to 'Core'
To be in line with the content of $SUPPORT_MAP, a '7' was needed.
The script failed
Solution:
Added case centos to the case environment on "$lsb_dist"
Now the dist_version is evaluated to '7'
The script runs as expected
> Fixed install.sh for Centos7 with lsb_release command available

- install.sh
Use the `--release` option on Fedora to get the proper match in `SUPPORT_MAP`.
```
$ lsb_release --codename | cut -f2
TwentySix
$ lsb_release --release | cut -f2
26
```
> Use lsb_release --release for Fedora

- install.sh
Rasbpian repo has been updated to 17.09.0-ce which includes a fix for
docker service calls on arm architecture, hence the removal of the old
apt repo for raspbian.
Also yakkety is no longer supported in the Docker CE releases so it is
effectively removed from the install script support
> Removes yakkety support, removes old raspbian repo

- Jenkinsfile
- Makefile
- install.sh
Adds temporary support for Ubuntu Artful while we wait to get packages
up, after we do get packages up we should delete the lines denoted `#TODO: DELETE HERE`
> Add temporary Ubuntu Artful support

- Jenkinsfile
- install.sh
Artful repositories for download.docker.com just went live for the test
channel, this should make the redirect unneccessary.
> Removes temporary redirect for artful repositories

- Jenkinsfile
- install.sh
This fix is to remedy users who are experiencing issues with Fedora 27,
released on November 15, 2017.
Once we have repositories up for Fedora 27 the designated lines should
be deleted to allow for use of the proper repositories
Relates to: https://github.com/docker/for-linux/issues/164
> Adds temporary support for Fedora 27

- Jenkinsfile
- Makefile
- install.sh
Debian Buster builds for Docker CE are now available on the test channel.
This PR adds:
* Support in the install script
* Support in the Makefile checks
* Support in the `Jenkinsfile`
Relates to: https://github.com/docker/for-linux/issues/102
> Add debian buster to install script

- Jenkinsfile
- install.sh
Adds the following distros (aarch64):
* Ubuntu Zesty
* Debian Jessie
* Debian Stretch
Debian Jessie for aarch64 needs backport repos since libseccomp2 does
not exist on the main aarch64 repos.
Should coincide with the release of `17.12.0-ce`
CI will most likely fail until the release of `17.12.0-ce-rc4`
> Add new aarch64 distros

- install.sh
Not needed anymore with the release of `17.12.0-ce`
https://download.docker.com/linux/fedora/27/x86_64/
Signed-off-by: Eli Uriegas <seemethere101@gmail.com>
> Remove Fedora 27 repo hardcoding

- install.sh
Support was supposed to be removed a while ago.
Fedora 24 EOL on [August 8, 2017](https://fedoramagazine.org/fedora-24-eol/)
Signed-off-by: Eli Uriegas <seemethere101@gmail.com>
> Remove Fedora 24 support

- install.sh
`lsb_release` in OSMC returns `osmc`, causing the install script to incorrectly assume that it is running stock Debian. This causes `"$(uname -m)-$lsb_dist-$dist_version"` to return `armv6l-debian-jessie` instead of the correct value `armv6l-raspbian-jessie`.
This pull request adds a special test for this case and ensures the correct distribution is set.
> Detect OSMC and install the correct package.

- Jenkinsfile
- Makefile
Ubuntu Zesty repositories have moved and the official docker images do not contain the correct repositories
CI Failures looked like:
```
W: The repository 'http://archive.ubuntu.com/ubuntu zesty Release' does not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu zesty-updates Release' does not have a Release file.
W: The repository 'http://archive.ubuntu.com/ubuntu zesty-backports Release' does not have a Release file.
W: The repository 'http://security.ubuntu.com/ubuntu zesty-security Release' does not have a Release file.
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/zesty/universe/source/Sources  404  Not Found [IP: 91.189.88.161 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/zesty-updates/universe/source/Sources  404  Not Found [IP: …
```
> Removes Ubuntu Zesty from testing pipeline

- Jenkinsfile
- install.sh
Based off new distributions added in https://github.com/docker/docker-ce-packaging/pull/71
Should add support for `aarch64` for:
* Fedora 26
* Fedora 27
* Centos 7
DO NOT MERGE UNTIL THE RELEASE OF `18.02.0-ce-rc1`
> Adds new rpm based aarch64 distros

- install.sh
Both distributions have reached their EOL and will no longer be supported in Docker CE.
This adds a way to remove them from the script while giving proper warning to affected users.
> Add deprecation notices for zesty and f25

- Makefile
- install.sh
VERSION pinning is something that people have been asking for, for a
while so this attempts to add that in.
Should work in most scenarios aside from incomplete VERSIONS.
IE: If you have the `test` channel enabled and try to install `17.12`
for example, the script will instead try to install rc2 since that is
the latest VERSION in the results.
Should also work with nightly builds like pinning to a date, or a
specific git SHA
Relates to #61 as well as https://github.com/docker/machine/issues/4091
Usage would be similar to `CHANNEL` pinning:
```
curl -fsSL get.docker.com | VERSION=17.12.0-ce sh
```
> Add VERSION pinning to the installation script

- install.sh
This is needed to allow package install of specific versions because of upcoming package name format change.
Without this PR, there would not be a match for deb packages:
```
apt-cache madison 'docker-ce' | grep '18.04.0~ce~beta1.*-0~ubuntu' | head -1 | cut -d' ' -f 4
```
With this PR, will be able to match deb packages:
```
apt-cache madison 'docker-ce' | grep '18.04.0~ce~.*beta1.*-0~ubuntu' | head -1 | cut -d' ' -f 4
18.04.0~ce~1.1.beta1-0~ubuntu
```
Similarly without this PR for rpm packages:
```
yum list --showduplicates 'docker-ce' | grep '18.04.0\.ce\.beta1.*el' | tail -1 | awk '{print $2}'
```
And with this PR, able to match rpm packages:
```
yum list --showduplicates 'docker-ce' | grep '18.04.0\.ce.*beta1.*el' | tail -1 | awk '{print $2}'
18.04.0.ce-1.1.beta1.el7.centos
```
> relax the regex to match packages easier

- install.sh
Only valid right now for nightly releases, maybe we should put a safeguard for that?
> Add ubuntu bionic

- install.sh
Needed to unblock nightly build verifications.
Adds Fedora 28 to the support map since it'll be available in nightly builds as soon as this script is uploaded
> Add fedora 28

- install.sh
Makes it so that the repo that's enabled is only the channel that we
specify.
Was the case where it'd automatically enable stable without explicitly
asking if we want stable enabled.
> Set to explictly disable all repos for RPM first

- Jenkinsfile
- Makefile
- install.sh
Relates to:
- https://github.com/docker/docker-ce-packaging/pull/212 Add initial scripts for Fedora 29
- https://github.com/docker/docker-ce-packaging/pull/256 [18.09 backport] Add initial scripts for Fedora 29
- https://github.com/docker/for-linux/issues/430 Please provide repo for docker-ce on Fedora 29
> Add Fedora 29, and remove Fedora < 28

- rootless-install.sh
This script installs the latest nightly build of rootless docker without requiring privileges.
It is meant to be loaded from either https://rootless.docker.com or https://get.docker.com/rootless
Tested in Ubuntu 18.04, 16.04, Debian 9, 8, Fedora 28, CentOS 7.5
For unsquashed version with previous review comments see https://github.com/tonistiigi/docker-install/pull/1
@AkihiroSuda @tiborvass 
@seemethere @andrewhsu @thaJeztah 
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>
Signed-off-by: Tibor Vass <tibor@docker.com>
> rootless: add rootless docker install script

- install.sh
Looks like "this value will automatically get changed" may
not be correct, as installing with this script enabled the
"edge" channel.
```
DRY_RUN=1 ./install.sh 
...
yum install -y -q yum-utils
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum-config-manager --disable docker-ce-*
yum-config-manager --enable docker-ce-edge
yum makecache
yum install -y -q docker-ce
```
fixes https://github.com/docker/docker-install/issues/77
> Use "stable" as default channel

- Jenkinsfile
- install.sh
This reverts commit 40b1b763998f478b3774d93763ad33eacc77def8, reversing
changes made to 26dda3d66987a707ec01f6fc2485bd0d379f7fee.
> [TAR-571] Remove the ads

- install.sh
Adds an error message if the distribution is not supported by
this script.  Previously the script would exit without a message
which didn't give much hints as to the problem.
Signed-off-by: Russell Cardullo <russellcardullo@gmail.com>
> Add an error message when the distribution is not supported

- install.sh
For some reason searching for some packages with apt-cache madison has
a result with leading whitespaces while others do not have the leading
whitespaces. Opting here to just remove all leading/trailing whitespaces
when accounting for results to make it consistent.
> TAR-666: Fix inconsistent whitespace in apt-cache results

- rootless-install.sh
**Description**
Add a configurable BIN folder for installation of rootless docker.  It's based on the request on Issue #100 
Not sure, but I can provide a statement in the README or instructions here for the user to set DOCKER_BIN if they wish to install it elsewhere
> Docker rootless bin folder

- Jenkinsfile
- Makefile
- install.sh
Simplifies CI to run through a simple `make test` target that has an
underlying `TEST_IMAGE` variable which determines the distribution to
run on.
Also changes the Jenkinsfile to be declarative since the old one kind of
sucked.
Also adds a test for version pinning since that's something we rely on a
lot.
> [TAR-916] Simplify CI, it was too complicated

- Makefile
- install.sh
the envsubst wasn't working correctly on ubuntu due to the `$` getting
stripped by make during the `addprefix`
Should now work correctly no matter what distribution you're on.
Bug was introduced in #131 
Also fixes the `build` target not pointing to anything
> [TAR-917] ci: Update addprefix to add another `$`

- install.sh
An interactive step is needed by libssl1.1:amd64 to config itself. User must chose Yes/No about "Restart services during package upgrades without asking?" via frontend. "DEBIAN_FRONTEND=noninteractive" will make default options be chosen and no interruption in the process.
This is tested on Ubuntu 18.
> Fix pending issue by interactive installation

- .github/workflows/ci.yml
- GH Actions: set 5 minute timeout for the tests
GitHub Actions have a default timeout of 6 hours, which is waaaay to high.
This updates the timeout to 5 minutes (they currently run in just over a minutes, so for now this should be enough).
- GH Actions: remove 18.09 as it reached EOL
> Update GitHub Actions configuration

- install.sh
Running `curl https://get.docker.com | sh` on macOS / WSL on Windows may lead to problems. Warn the user and give a suggestion to user Docker Desktop instead.
-  Check if a user runs this script on macOS, suggest Docker Desktop and abort.
```
ERROR: Unsupported operating system 'macOS'
Please get Docker Desktop from https://www.docker.com/products/docker-desktop
```
-  Check if a user runs this script in a WSL 1 / WSL 2 distro, suggest Docker Desktop for Windows and delay execution.
```
WSL DETECTED: We recommend using Docker Desktop for Windows.
Please get Docker Desktop from https://www.docker.com/products/docker-desktop
You may press Ctrl+C now to abort this script.
+ sleep 20
```
Fixes #165
> [DESKTOP-2757] Check for macOS and WSL and suggest Docker Desktop

- install.sh
Cleanup unsupported dists, removing some code.
The script will output `ERROR: Unsupported distribution '$lsb_dist'` on these distributions.
> Cleanup unsupported dists

- rootless-install.sh
`/tmp/docker-$(id -u)` is not a good candidate as `$XDG_RUNTIME_DIR`, because it might be already created by another user.
The new path is `$HOME/.docker/run`.
This commit does not affect systemd-based hosts.
> rootless-install.sh: use safer XRD on non-systemd hosts

- rootless-install.sh
Previously, it was failing with the following error when `$BIN` is not present in `$PATH`:
```
+ /home/vagrant/bin/dockerd-rootless-setuptool.sh install
[ERROR] dockerd-rootless.sh needs to be present under $PATH
```
> rootless (nightly): set PATH="$BIN:$PATH" before running setup tool

- rootless-install.sh
I think that the \n inside `echo "# Make sure the following environment variables are set (or add them to ~/.bashrc):\n"` is unnecessary.  
Maybe we should remove it.
> fix typo in rootless-install.sh

- rootless-install.sh
20.10.0-beta1  will be installable with `curl -fsSL https://get.docker.com/rootless | CHANNEL=test sh`
> rootless-install.sh: support CHANNEL=test (20.10.0-beta1)

- install.sh
When upgrading docker from versions older than v1.10, the image store must be migrated for the content-addressable store.
Docker 1.10 was released more than 5 years ago, so people running versions older than that, probably have more urgent things to be concerned about, so removing this warning.
> remove warning about pre-1.10 update

- install.sh
internal ticket: [POS-27]
supersedes / replaces https://github.com/docker/docker-install/pull/195 (except for the "containerd.io" part)
closes https://github.com/docker/docker-install/pull/195
The scripts is using "--no-install-recommends" to provide a more minimal install, and to prevent installing "latest" version of (e.g.) the engine when installing the CLI.
This patch:
- adds some utilities to compare versions
- skips CLI-version discovery on older versions (before 18.09)  which did not have separate packages for the CLI
- on versions 20.10 and up (or if no version was specified), also install the scan cli plugin (support for cli plugins was added   in docker 19.03, but not installing on that version by default)) 
[POS-27]: https://docker.atlassian.net/browse/POS-27
> deb: explicitly install docker-ce-cli, scan-plugin, and docker-ce

- install.sh
This adds a deprecation warning for distro versions that reached EOL, and for which we no longer maintain updates.
Note that the list of versions for which we produce warnings is not "complete", and only contains versions that either reached EOL recently, or LTS versions that may still be commonly in use.
With this patch;
Running inside a fedora:32 container:
DEPRECATION WARNING
This Linux distribution (fedora 32) reached end-of-life and is no longer supported by this script.
No updates or security fixes will be released for this distribution, and users are recommended
to upgrade to a currently maintained version of fedora.
Press Ctrl+C now to abort this script, or wait for the installation to continue.
^C
Running inside an ubuntu:xenial container:
DEPRECATION WARNING
This Linux …
> Add deprecation warning for Ubuntu Xenial (16.05) and other EOL distro versions

- install.sh
follow-up to https://github.com/docker/docker-install/pull/238
Jessie reached EOL quite some time ago, and we do not support Debian/Ubuntu derrivatives, so removing code for Kali Linux.
> remove code for Debian Jessie and "Kali Linux"

- install.sh
carry of https://github.com/docker/docker-install/pull/241
> Add support for debian bullseye and deprecate apt-key (carry 241)

- install.sh
gpg prompt for overwriting the keyring ( if it exist or installed before ) file and by adding `--yes` will fix it.
```
You may press Ctrl+C now to abort this script.
+ sleep 20
+ sh -c apt-get update -qq >/dev/null
+ sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sh -c curl -fsSL "https://download.docker.com/linux/debian/gpg" | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
File '/usr/share/keyrings/docker-archive-keyring.gpg' exists. Overwrite? (y/N) 
```
> Fix non-interactive installation

- install.sh
- fixes https://github.com/docker/docker-install/issues/244
- closes https://github.com/docker/docker-install/pull/256
- closes https://github.com/docker/docker-install/pull/269
Some environments may have a non-standard (non 022) umask set, in which case
the keyring would not get read-permissions for all users, which lead to errors
during install:
W: GPG error: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7EA0A9C3F273FCD8
This commit changes the permissions of the file, so that it's world-readable.
See https://stackoverflow.com/a/68764068
Co-Authored-By: ManhIT <manhit@s-developers.com>
Co-Authored-By: Hervé M <hmag@users.noreply.github.com>
Signed-off-by: Sebastiaan van Stijn <github@gone.nl>
> install.sh: set read-permissions for environments with non-standard umask

- rootless-install.sh
Fixes some shellcheck linting warnings:
- [SC2034][SC2034]: "SCRIPT_COMMIT_SHA appears unused. Verify use (or export if used externally)."
- [SC2046][SC2046]: "Quote this to prevent word splitting"
- [SC2002][SC2002]: "Useless cat. Consider cmd < file | .. or cmd file | .. instead"
- [SC2064][SC2064]: "Use single quotes, otherwise this expands now rather than when signalled."
[SC2034]: https://github.com/koalaman/shellcheck/wiki/SC2034
[SC2002]: https://github.com/koalaman/shellcheck/wiki/SC2002
[SC2046]: https://github.com/koalaman/shellcheck/wiki/SC2046
[SC2064]: https://github.com/koalaman/shellcheck/wiki/SC2064
> rootless-install.sh: fix some shellcheck warnings

- install.sh
`zypper install -y -q <package>` throws an error "The flag q is not known". Fixed the same.
Signed-off-by: Prabhav Thali <Prabhav.Thali1@ibm.com>
> Fix zypper command syntax

- install.sh
- handles the remaining bits of https://github.com/docker/docker-install/pull/195
- supersedes https://github.com/docker/docker-install/pull/195
- closes https://github.com/docker/docker-install/pull/195
While the script isn't intended for updating existing installations,
some users use it for that purpose, and when doing so may end up in
a situation where only the docker packages are updated, but containerd
is kept at the already installed version.
This patch explicitly installs the containerd.io package so that running
the script on an existing installation also updates the containerd.io
package to the latest version.
Docker packages before 18.09 bundled containerd in the docker-ce package,
so this step is made options based on the version that's requested to be
installed (defaults to …
> Explicitly install containerd.io to handle upgrades

- install.sh
- relates to https://github.com/docker/docker.github.io/pull/14813
See https://tracker.debian.org/news/1305679/accepted-apt-240-source-into-unstable/:
* Install an empty /etc/apt/keyrings directory.
This directory is intended to provide an alternative to
/usr/share/keyrings for placing keys used with signed-by.
See also https://wiki.debian.org/DebianRepository/UseThirdParty?action=diff&rev2=47&rev1=46
(which was edited following a discussion with the APT maintainers about the expected usage):
> If future updates to the key will be managed by an apt/dpkg package as
> recommended below, then it SHOULD be downloaded into `/usr/share/keyrings`
> using the same filename that will be provided by the package. If it will
> be managed locally , it SHOULD be downloaded into `/etc/apt/keyrings` …
> Update to use /etc/apt/keyrings per APT maintainers recommendations

- install.sh
- relates to https://github.com/docker/docker-install/pull/69
These checks were originally added in 3217c543b4c0d54944ec4fb1133510aa8ea06eb7 (https://github.com/docker/docker-install/pull/69),
which added a `REPO_FILE` variable. While it's with good intent to do a check
if the URL is valid, there are some issues with these checks;
The checks depend on `curl`, but are executed _before_ `pre_reqs` are installed,
so will produce an error if `curl` is not found;
./install.sh
./install.sh: line 469: curl: command not found
Error: Unable to curl repository file https://download.docker.com/linux/fedora/docker-ce.repo, is it valid?
The checks are currently always performed, also if `DRY_RUN=1` is enabled;
DRY_RUN=1 REPO_FILE=no-such.repo ./install.sh
Error: Unable to curl repository file …
> fix "REPO_FILE" checks always running, also with "dry run" enabled

- install.sh
- relates to https://github.com/docker/docker-ce-packaging/pull/818
The version-format of the packages changed in the docker-ce-packaging repo; https://github.com/docker/docker-ce-packaging/commit/39772a761dfdf810cc23a1ec6084ea3100e6abf0
Which caused the script to fail when specifying a version:
INFO: Searching repository for VERSION '23.0.0-rc.2'
INFO: apt-cache madison 'docker-ce' | grep '23.0.0.*rc.2.*-0~debian' | head -1 | awk '{$1=$1};1' | cut -d' ' -f 3
ERROR: '23.0.0-rc.2' not found amongst apt-cache madison results
Looking at that search, it seemed like it was overly strict;
- matching the distro (debian, ubuntu, or raspbian), which should not be needed, assuming the package repository has been set up correctly (which the script does in earlier steps).
- matching the "0" prefix, …
> fix matching of package versions on debian, ubuntu, and raspbian

- install.sh
- supersedes, closes https://github.com/docker/docker-install/pull/333
- relates to https://github.com/docker/docker-install/pull/44
- relates to https://github.com/moby/moby/issues/44900
The installation for deb packages used a `--no-install-recommends` to skip "recommended" packages. This flag was added in ab5553e3027fdf53c5b68ef543f7437dc15c33df (https://github.com/docker/docker-install/pull/44) to work around an issue on Ubuntu 17.10 (which had aufs-tools as recommended dependency), causing the kernel to be updated.
While "recommended" packages _can_ be omitted during installation, they are a "strong" recommendation, and should really be installed by default:
> Recommends
>
> This declares a strong, but not absolute, dependency.
> The Recommends field should list packages that would …
> deb: remove --no-install-recommends

- install.sh
- relates to https://github.com/docker/docker-install/pull/248
- relates to https://github.com/docker/docker-install/pull/287
This variable was introduced in 63fb2060c9436bb3ad4434bdbf55f92824428e8e (https://github.com/docker/docker-install/pull/248), but was later refactored in ab0389264936174e064d0fcf3ab39d2ee8d9b976 (https://github.com/docker/docker-install/pull/287) aligned the installation steps for SLES with the other distros (using the version of the "docker-ce" package itself, as those versions always match).
This patch removes the unused `rootless_pkg_version` variable, and the code to resolve that version.
> SLES: remove unused rootless_pkg_version

- install.sh
- follow-up to https://github.com/docker/docker-install/pull/335
Now that 0095742fb5d923f876e720731073c541f47f0f79 (https://github.com/docker/docker-install/pull/335) removed the "--no-install-recommends" option for all packages, we no longer need to special-case installation of the rootless-extras
package.
This patch moves the package together with other conditional packages for 20.10 and up. The order of these conditionals was updated to match the equivalent steps of the RPM packages.
> deb: simplify version-conditional installs

- install.sh
Fedora 35 reached EOL on December 13, 2022, and we're no longer building new packages for it;;
https://docs.fedoraproject.org/en-US/releases/eol/
> print deprecation warning for Fedora 35 and before

- install.sh
- carries https://github.com/docker/docker-install/pull/327
- closes https://github.com/docker/docker-install/pull/327
We published packages now for Debian 12 (bookworm) for testing, so we can
update this to use the correct version;
https://download.docker.com/linux/debian/dists/bookworm/pool/stable/amd64/
> Fix installation on debian testing (bookworm) (carry 327)

- .github/workflows/ci.yml
- Makefile
- updating the "version" to install to 20.10 (previous version)
- remove ubuntu 18.04, as it's EOL soon
- add last 2 LTS versions of Ubuntu
- add centos:9 (stream)
Also updated to actions/checkout@v3
> gha: update distros and version to install

- install.sh
This explict install was added because docker 20.10 did not have an explicit dependency on the plugin. The current release of the Docker CLI (23.0) already has a "Recommends:" dependency on the plugin, and 0095742fb5d923f876e720731073c541f47f0f79 (https://github.com/docker/docker-install/pull/335) removed the "--no-install-recommends", so fresh installs of Docker 23.0 will already install this plugin through that dependency.
Removing the explicit install, because the scan-cli-plugin has been deprecated, and will no longer receive updates, so we don't want it to be installed for the upcoming 24.0 release when using this script. see; https://github.com/docker/scan-cli-plugin/blob/b69ac460a6c23243b858326f0e26f6bd202ca781/internal/deprecation.go#L13-L15 …
> remove redundant install for scan-cli-plugin

- .github/workflows/ci.yml
Looks like their package repositories are having a bad day, or changes were made (again);
+ sh -c 'yum install -y -q yum-utils'
Error: Failed to download metadata for repo 'baseos': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
> gha: temporarily disable CentOS 9

- .github/workflows/ci.yml
- This reverts commit c435f9da96d0e5ff3bf0ec32bf2567fd823ff389 (https://github.com/docker/docker-install/pull/352).
> Revert "gha: temporarily disable CentOS 9"

- install.sh
- rootless-install.sh
I noticed a discrepancy in the main install script where nightly was marked as unmaintained in a comment but it was also flagged as deprecated in the warning message.
I brought this up with @thaJeztah on Slack and he mentioned he thinks it's ok to officially deprecate the nightly channel.
When I searched this repo for references to nightly I also found a reference to it in the rootless-install script. We didn't discuss that on Slack but I did set things up to deprecate it there as well. I used a similar pattern to what's in the main install script.
> Deprecate the nightly channel

- rootless-install.sh
25.0.0-beta.1 is now available via the test channel.
> Update rootless-install.sh with 25.0.0-beta.1

- install.sh
Dropped support for SLES 15-sp3 as it is EOL. 
Updated the opensuse_repo URL as for SLES 15-SP5, container-selinux is present in the Opensuse_factory repo. And made it generic for SLES 15-sp4 and SLES 15-sp5.
Signed-off-by: Prabhav Thali [Prabhav.Thali1@ibm.com](mailto:Prabhav.Thali1@ibm.com)
> Drop SLES 15-SP3 support

- install.sh
- relates to https://github.com/docker/docs/pull/19138
Current distro versions now allow the GPG key to be stored as an `.asc` file, which simplifies installation. Changing the file extension for the GPG key to .asc lets apt-get know the GPG key is in ASCII armor format, in which case there is no need to "dearmor", and we no longer need gpg as a pre-requisite. Instructions for manual installation on Debian based distros were updated in our documentation through [docker/docs@33befd6].
It's common for users to install packages in a combination of the convenience script and manual (e.g. to update the packages after install, or vice-versa). Given that both the script and the manual steps configure the repository, we want those steps to align, otherwise (potentially?) warnings / errors may …
> update script to use .asc, remove gpg as pre-requisite

- install.sh
... instead of yum. The yum command is no longer available by default in recent versions.
Closes #394
> CentOS/RHEL: Use dnf if available

- install.sh
We stopped building packages for these, and especially 23.04 (ending with `04`) may get confused for an LTS version (which it isn't), so let's make sure it produces warnings / errors for this.
> Add deprecation warnings for Ubuntu 22.10 (Kinetic Kudu) and Ubuntu 23.04 (Lunar Lobster)

- rootless-install.sh
Assign `CHANNEL` variable between `STABLE_LATEST` and `TEST_LATEST` to
spread them apart so they don't appear in diff.
This allows to limit merge conflicts when there are two separate PRs
that update one of the versions.
> rootless-install: Add spacing to limit merge conflicts

- .github/workflows/ci.yml
- relates to https://github.com/docker/runtime-team/issues/119
- relates to https://github.com/docker/docker-install/pull/426#issuecomment-2199735994
---
- CentOS 7 reached EOL
- Adding Ubuntu 24.04 (LTS)
- Update the "old" engine version to install to 26.1
> gha: remove CentOS 7 (EOL), add Ubuntu 24.04, use engine 26.1

- install.sh
- relates to https://github.com/docker/runtime-team/issues/119
- relates to https://github.com/docker/docker-install/pull/427
With this patch:
```bash
sh -c install.sh
DEPRECATION WARNING
This Linux distribution (centos 7) reached end-of-life and is no longer supported by this script.
No updates or security fixes will be released for this distribution, and users are recommended
to upgrade to a currently maintained version of centos.
Press Ctrl+C now to abort this script, or wait for the installation to continue.
```
> add deprecation warning for CentOS 7 / RHEL 7

- install.sh
relates to:
- https://docker.atlassian.net/browse/POS-1687
- https://github.com/docker/docs/pull/20174
- https://github.com/docker/docker-install/pull/248
This check was added in 63fb2060c9436bb3ad4434bdbf55f92824428e8e (https://github.com/docker/docker-install/pull/239 / https://github.com/docker/docker-install/pull/248), at which time we did not provide packages fro RHEL on architectures other than s390x.
We now provide packages for RHEL 8 and 9 for amd64 (x86), arm64, and s390x, so we can remove this check.
Note that we do not (yet?) provide packages for ppc64le, but this is more of a niche use-case, so not adding a special condition for that, as we don't provide that check for other distros.
> remove check for RHEL only being available on s390x

- install.sh
- relates to https://github.com/docker/docs/pull/13718
- fixes https://github.com/docker/docker-install/issues/224
This package is no longer needed on all current distro versions we support. From the package description (https://packages.debian.org/buster/apt-transport-https);
> This is a dummy transitional package - https support has been moved into the
> apt package in 1.5. It can be safely removed.
Verifying the version of apt that's available in Ubuntu and Debian:
Ubuntu:
docker run --rm ubuntu:xenial apt --version
apt 1.2.35 (amd64)
docker run --rm ubuntu:17.04 apt --version
apt 1.4.6 (amd64)
docker run --rm ubuntu:17.10 apt --version
apt 1.5.2 (amd64)
docker run --rm ubuntu:18.04 apt --version
apt 1.6.14 (amd64)
docker run --rm ubuntu:20.04 apt --version
apt 2.0.6 (amd64)
Debian: …
> remove apt-transport-https from pre_reqs

- install.sh
Ubuntu 18.04 LTS reached end of standard support. Expanded Security Maintenance
(ESM) is available, but requires a subscription, and we don't provide packages
for those.
- https://wiki.ubuntu.com/Releases
- https://ubuntu.com//blog/18-04-end-of-standard-support
Debian 10 reached EOL and we're no longer building packages for it.
Fedora 38 and older reached EOL
CentOS 8 stream reached EOL, and we're no longer building packages for it.
> add deprecation warnings for Ubuntu 18.04 (bionic), Debian, Raspbian 10 Buster, Fedora <= 38, and CentOS (Stream) 8

- install.sh
Ubuntu 23.10 reached EOL on July 11, 2024: https://fridge.ubuntu.com/2024/07/17/ubuntu-23-10-mantic-minotaur-reached-end-of-life-on-july-11-2024/
> add deprecation warning for Ubuntu 23.10 (Mantic Minotaur) (EOL: July 11, 2024)

- install.sh
- rootless-install.sh
- relates to https://github.com/docker/docker-ce-packaging/pull/1058
- relates to https://github.com/docker/docker-ce-packaging/pull/1059
- relates to https://github.com/rpm-software-management/dnf5/issues/1603
The `-y` and `-q` options are global options, and can be set before the
command that's run. There's some ambiguity in the USAGE output of different
versions (`yum`, `dnf`, `dnf5`)
yum always outputs the same usage, but shows that options go _before_
the command;
yum --help
Usage: yum [options] COMMAND
yum install --help
Usage: yum [options] COMMAND
dnf (dnf4) is ambiguous; when showing usage for `install` it shows the
options to be set _after_ the command;
dnf install --help
usage: dnf install [-c [config file]] [-q] [-v] [--version] ....
but the global `--help` shows them to be …
> add support for dnf5 (in preparation of fedora 41)

- install.sh
- updates https://github.com/docker/docker-install/pull/359
commit 766b70c5be1a000e09a159aedd0d2375dee84ded quoted these values to prevent globbing, but used single quotes. However, these commands are executed with `sh -c` using single quotes, which makes the output hard to read because of the embedded quotes being escaped.
This patch changes to use double-quotes, which should still prevent globbing to happen, but make the output more readable.
Before:
CHANNEL=test ./install.sh
...
Adding repo from: https://download.docker.com/linux/centos/docker-ce.repo
+ '[' test '!=' stable ']'
+ sh -c 'dnf config-manager --set-disabled '\''docker-ce-*'\'''
+ sh -c 'dnf config-manager --set-enabled '\''docker-ce-test'\'''
+ sh -c 'dnf makecache'
After:
CHANNEL=test ./install.sh
...
Adding repo from: …
> use double-quotes to make output more readable

- install.sh
> Update docker support for s390x

- rootless-install.sh
> rootless: update test version to 28.1.0-rc.1

- install.sh
When using a staging download URL (containing "-stage" in the URL), and no explicit repo was provided automatically use the staging repo file as well.
(This only affects DNF distros)
So it's sufficient to do:
```
curl -L get.docker.com | DOWNLOAD_URL="https://download-stage.docker.com" sh -
```
instead of
```
curl -L get.docker.com | REPO_FILE="docker-ce-staging.repo" DOWNLOAD_URL="https://download-stage.docker.com" sh -
```
> install: Default to staging repo file for staging download URL

- rootless-install.sh
Due to regression in the dockerd-rootless.sh script: https://github.com/moby/moby/pull/49727#discussion_r2049365900
> rootless: revert 28.1.0 from stable

- .github/workflows/ci.yml
Test the rootless install in CI
> gha: Add workflow to test rootless install

- rootless-install.sh
> rootless: update test version to 28.2.0-rc.1

- .github/workflows/ci.yml
- install.sh
Ubuntu 20.04 reached end of support on April 30. There's still commercial ESM (Extended Security Maintenance) support, but we don't account for that in our packages; https://ubuntu.com/blog/ubuntu-20-04-eol-for-devicesional
> add ubuntu 20.04 "focal" (LTS) to list of EOL distros, use docker 27.5 for versioned install

- install.sh
- relates to https://github.com/docker/docker-ce-packaging/pull/1190
Install the model-runner CLI plugin.
> install "docker-model-plugin"

- install.sh
On ubuntu bionic and some other debian/versions, the docker-model-plugin package is missing. The suggestion was to just install the package named docker-buildx-plugin in the version 23 check, while moving the missing package docker-model-plugin to a new "version 28.2" check.
See: https://github.com/docker/docker-install/issues/509
> Avoid installing missing packages for version 23 (and moving them to 28.2)

- Makefile
Fixes `the input device is not a TTY`
> gha: Fix stdin tty attach failing the deploy

- install.sh
The `--setup-repo` flag allows users to add Docker package repositories to without automatically installing Docker packages.
This is useful for scenarios where users want to configure the repository but handle package installation separately.
> Add --setup-repo option to configure repositories without installing packages
