docker/docker-install

Makefile, install.sh
shellcheck and os-release files from various distros
=> cleanup in prep for refactor

install.sh
Moved distribution checks to a function that just checks
`/etc/os-release` (which also fixes raspbian installation in
environments that do not have the lsb_release command).
Also shuffles around some TODO messages.
=> Simplify distribution checks, fix raspbian support

README.md
Testing was changed in #15, this updates the README to reflect that
=> Remove outdated testing information

install.sh
There was a discussion on #18 about re-adding mirrors for the install script.
As of now we are ready to re-add support for the Aliyun mirror.
=> Re-adds Aliyun mirror option

install.sh
=> Removes mixed tabs and spaces

.gitignore
=> Adds log output from `make check` to gitignore

install.sh
It could be annoying not to be able to see what's going on in the install script, this flag adds a way to see the commands that will be run on your machine, output can actually be used as shell script.
```shell
curl -fsSL https://github.com/seemethere/docker-install/raw/add_dry_run/install.sh | DRY_RUN=1 sh
```
=> Adds dry run flag for the paranoid

install.sh
=> Fixes new shellcheck errors SC2222 SC2221

Jenkinsfile, Makefile, install.sh
Can verify the install of ppc64le versions
Signed-off-by: Corbin <corbin.coleman@docker.com>
=> Add ppc64le verify to install.sh, Makefile, and Jenkinsfile

install.sh
Doesn't seem to be needed anymore
Relates to #43 
=> Remove software-properties-common

Jenkinsfile
Signed-off-by: Eli Uriegas <seemethere101@gmail.com>
=> Update nodes to test on for ppc64le

install.sh
=> Allow overwriteable download url

install.sh
=> Add debian buster for arm64

README.md, install.sh
Avoid having a user do exactly what we tell them and getting an error...
```
sven@yoga260:~/src/csiro/sima/docker-compose-files$ curl -fsSl get.docker.com
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>CloudFront</center>
</body>
</html>
```
=> fix documented curl line to avoid 301 Moved Permanently error

Jenkinsfile, Makefile, install.sh
Remove Ubuntu Artful since it is end of life.
=> Remove Ubuntu Artful since it is end of life.

Jenkinsfile, install.sh
=> Remove Debian Wheezy since it is end of life

install.sh
Ran into a merge conflict when trying to rebase #80 so I just created my own PR based off of the latest master
=> Add ubuntu cosmic

Jenkinsfile, install.sh
Just let the script run on whatever it's trying to be ran on.
Signed-off-by: corbin-coleman <corbin.coleman@docker.com>
=> TAR-238 Remove SUPPORT_MAP

install.sh
=> Remove limit on Fedora versions

rootless-install.sh
Signed-off-by: Andrew Hsu <andrewhsu@docker.com>
=> update the script location comment

rootless-install.sh
@AkihiroSuda
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>
=> rootless: prefer overlay2

install.sh
Tested with the following versions:
```bash
#!/usr/bin/env bash
set -e
RUN="docker run --rm -it -v $(pwd):/v -w /v"
for distro in ubuntu:bionic debian:stretch centos:7 fedora:29; do
for version in 18.09.2 18.06.1; do
echo "${distro}, VERSION: ${version}"
${RUN} "${distro}" sh -c "VERSION=${version} sh install.sh && docker --version"
done
done
```
=> TAR-666: Add version pinning for docker-ce-cli

install.sh
Signed-off-by: Micha Felle <micha@dietpi.com>
=> Add support for Debian Buster

rootless-install.sh
Signed-off-by: Akihiro Suda <akihiro.suda.cz@hco.ntt.co.jp>
=> rootless-install.sh: bump up to 19.03.5

install.sh, rootless-install.sh
Without the URL of the docs, it is hard to understand the intention of the script.
=> add URLs of docs to headers

rootless-install.sh
Fixes https://github.com/docker/docker-install/issues/137
=> Changed systemd target of rootless docker to default

install.sh
Signed-off-by: Tibor Vass <tibor@docker.com>
I think it's safe to merge, even though this won't work until the next release.
=> Make script work on RHEL

rootless-install.sh
`dockerd-rootless-setuptool.sh` is the new standard way to set up the systemd unit file.
https://github.com/moby/moby/blob/master/contrib/dockerd-rootless-setuptool.sh
The usage of `rootless-install.sh` stays same.
=> rootless: call dockerd-rootless-setuptool.sh for $CHANNEL=nightly

README.md, install.sh, rootless-install.sh
- install.sh: install docker-ce-rootless-extras explicitly
Fix #212
- install.sh: promote Rootless mode over "sudo usermod -aG docker me"
Fix #210
=> install docker-ce-rootless-extras explicitly + unrecommend `sudo usermod -aG docker me`

rootless-install.sh
Close https://github.com/docker/docker-install/issues/226
Close https://github.com/moby/moby/issues/42301
=> rootless-install.sh: print upgrade steps

rootless-install.sh
The which command is often missing.
ref: https://github.com/moby/moby/pull/42315
=> rootless-install.sh: use command -v instead of which

install.sh
carry of https://github.com/docker/docker-install/pull/239 with some whitespace removed
closes https://github.com/docker/docker-install/pull/239
=> Added support for sles (s390x) in installation script (carry 239)

install.sh
Added a generic fix for enabling SLES repos
=> Added a generic fix for enabling SLES repos

install.sh
This aligns the approach taken between rpm- and deb-based installations to first
collect the list of packages to install in a `$pkgs` variable, and then install
them all, instead of executing an install for each of them.
With this change:
Fedora
DRY_RUN=1 ./install.sh
dnf install -y -q dnf-plugins-core
dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
dnf makecache
dnf install -y -q docker-ce docker-ce-cli docker-scan-plugin docker-ce-rootless-extras
CentOS
DRY_RUN=1 ./install.sh
yum install -y -q yum-utils
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum makecache
yum install -y -q docker-ce docker-ce-cli docker-scan-plugin docker-ce-rootless-extras
Ubuntu
DRY_RUN=1 ./install.sh
apt-get update -qq >/dev/null …
=> align approach for packages to install between rpm and deb steps

install.sh
- carries https://github.com/docker/docker-install/pull/280
- closes https://github.com/docker/docker-install/pull/280
=> Add docker-compose-plugin package

install.sh
fixes https://github.com/moby/moby/issues/44906
closes https://github.com/docker/docker-install/pull/298
cc @tonistiigi @thaJeztah 
Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>
=> fix buildx install

rootless-install.sh
=> rootless: update test version to 24.0.0-beta.1

rootless-install.sh
release notes: https://github.com/moby/moby/releases/tag/v23.0.3
=> update rootless-install to 23.0.3

rootless-install.sh
release notes: https://github.com/moby/moby/releases/tag/v23.0.4
=> update rootless-install to 23.0.4

rootless-install.sh
release notes: https://github.com/moby/moby/releases/tag/v23.0.5
=> update rootless-install to 23.0.5

rootless-install.sh
Release notes: https://github.com/moby/moby/releases/tag/v24.0.0
=> Update rootless-install to 24.0.0

rootless-install.sh
=> rootless: update test version to 26.0.0-rc3

rootless-install.sh
=> rootless: update to 26.0.0

rootless-install.sh
=> rootless: update to 26.0.1

rootless-install.sh
=> rootless: update to 26.1.0

rootless-install.sh
=> rootless: update to 27.0.3

rootless-install.sh
- follow-up to https://github.com/docker/docker-install/pull/428
Cleaning up my local branches; I had this stashed as part of the above PR, but at the time decided to keep it for a follow-up 😂
=> rootless: move versions together

rootless-install.sh
=> rootless: update to 27.1.0

rootless-install.sh
=> rootless: update to 27.2.1

rootless-install.sh
=> rootless: update test version to 27.3.0-rc.2

rootless-install.sh
=> rootless: update test+stable versions to 27.3.0

rootless-install.sh
=> rootless: update test+stable versions to 27.3.1

install.sh
- relates to https://github.com/docker/docker-install/pull/441
- relates to https://github.com/rpm-software-management/dnf5/issues/1603
- relates to https://github.com/rpm-software-management/dnf5/pull/1671
This reverts commit 27f47c592a72999298581970a9d9339c14e842ba.
=> Remove workaround for dnf5 addrepo bug

install.sh
Fedora 39 and older reached EOL
=> add deprecation warning for Fedora 39 and older

rootless-install.sh
=> rootless: update test version to 27.4.0-rc.1

rootless-install.sh
=> rootless: update test version to 27.4.0-rc.2

rootless-install.sh
=> rootless: update test version to 27.4.0-rc.3

rootless-install.sh
=> rootless: update test version to 27.4.0-rc.4

rootless-install.sh
=> rootless-install.sh: bump up to 27.4.0

rootless-install.sh
rootless: update test version to 27.5.0-rc.1
=> rootless: update test version to 27.5.0-rc.1

rootless-install.sh
=> rootless: update test version to 28.0.0-rc.2

rootless-install.sh
=> rootless: update test version to 28.0.0

install.sh
=> install.sh: Add Debian "Trixie"

rootless-install.sh
=> rootless: update to 28.1.0

rootless-install.sh
=> rootless: update to 28.1.1

install.sh
Fedora 40 reached EOL on May 13, 2025;
https://docs.fedoraproject.org/en-US/releases/eol/
=> add deprecation notice for Fedora 40 (EOL)

rootless-install.sh
=> rootless: update test version to 28.3.0-rc.1

rootless-install.sh
=> rootless: update to 28.2.2

rootless-install.sh
=> rootless: update test version to 28.3.0-rc.2

rootless-install.sh
=> rootless: update to 28.3.1

rootless-install.sh
=> rootless: update to 28.3.2

Makefile, diff.sh
For easier usage in https://github.com/docker/docker-install-deploy
=> Makefile: extract diff to a separate script
